### ISSUE TITLE
GeoJSON encoding for Multipolygons

### ISSUE THREAD

**Issue by monkeybutter** [ctessum/geom#1]
First of all thank you very much for sharing your library, I think it's great!

I've noticed that when I try to encode a MultiPolygon as GeoJSON your library responds with:
`geojson: unsupported geometry type geom.MultiPolygon`

Do you think a geom.MultiPolygon should be encoded as:
`{"type": "FeatureCollection", "features": [{"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[...`

I can create a pull request to produce this behaviour but I just wanted to ask first, in case this should be done in a different way.

**Comment by monkeybutter** [comment]
What about adding this structs to geom/encoding/geojson/geojson.go?

```go 
type FeatureCollection struct {
	Type     string     `json:"type"`
	Features []*Feature ``json:"features"`
}
```
```go 
type Feature struct {
	Type       string                 `json:"type"`
	Id         string                 `json:"id"`
	Geom       Geometry               `json:"geometry"`
	Properties map[string]interface{} `json:"properties"`
}
```

**Comment by ctessum** [comment]
Sounds good to me!

**Comment by monkeybutter** [comment]
Thinking more about this issue, there are two separate issues when serializing into GeoJSON. One is the geometry itself and the other is the wrapping feature. What do you think about the proposal of having to Encode() methods, one just for geometries and the other as features:

https://gist.github.com/monkeybutter/2e51e2b42b04528436bf1566d79b43da
https://gist.github.com/monkeybutter/04d7aac0073c87e5a95c6ca843920235

The good thing is that now more objects could be serialized (multipoint, multilinestring, ...) as feature collections.

Other possibility is the Encode() method to return geometries encoded as features by default, which simplifies usability. Maybe there is a better way of doing this...

**Comment by monkeybutter** [comment]
Sample _test file for the proposal

https://gist.github.com/monkeybutter/5af0d956b1f9d269391f63bb3e20e4f8

**Comment by ctessum** [comment]
I don't use geojson that much, so I would be willing to defer to your judgement. This part was originally written by @twpayne so he may have input.

**Comment by twpayne** [comment]
I think it makes lots of sense to have separate code for geometries and features. This is exactly the approach I took in https://github.com/twpayne/go-geom/blob/master/encoding/geojson/geojson.go.

**Comment by monkeybutter** [comment]
Thanks for the example. I always thought MultiPolygon had to be encoded as a FeatureCollection of Polygons but I've just realised there is a GeoJSON MultiPolygon object. Then it's easier to extend the json encoder for this package to include serialization for Multipolygons just by adding a pointsssCoordinates() function to encode them. I'll try to come up with a proposal.
