### ISSUE TITLE
undefined: floats.EqualWithinULP

### ISSUE THREAD

**Issue by alemelis** [ctessum/geom#11]
Hello!

I'm trying to use this library in my project but I get this error when building

```
# github.com/ctessum/geom/proj
/Users/ale/go/pkg/mod/github.com/ctessum/geom@v0.2.11/proj/Proj.go:112:28: undefined: floats.EqualWithinULP
/Users/ale/go/pkg/mod/github.com/ctessum/geom@v0.2.11/proj/Proj.go:133:9: undefined: floats.EqualWithinULP
```

which refers to 
https://github.com/ctessum/geom/blob/6177566ea6a303e26ff58f61050b7bcaa7aae4a7/proj/Proj.go#L131-L136

From what I understand, that should be 

```go
scalar.EqualWithinULP(f1.Index(i).Float(), f2.Index(i).Float(), ulp) 
```

where [`scalar`](https://pkg.go.dev/gonum.org/v1/gonum/floats/scalar#EqualWithinULP) is imported from `"gonum.org/v1/gonum/floats/scalar"`

**Comment by ctessum** [comment]
FIxed by #12
