### ISSUE TITLE
Difference results in empty (non-closed) polygon

### ISSUE THREAD

**Issue by oceanful** [ctessum/geom#8]
Certain `difference` operations result in incorrect empty results. Here's a reproduction case with the following shapes:

![intersecting-shapes](https://user-images.githubusercontent.com/35951082/57044699-3fffe900-6c20-11e9-947c-fda6a613e57f.png)

```golang
blue := geom.Point{X: 120.0, Y: 120.0}.Buffer(100.0, 10)
red := geom.Point{X: 200.0, Y: 200.0}.Buffer(60.0, 10)
intersection := blue.Intersection(red)

fmt.Println(red.Difference(intersection))

// Result
[]
```

The correct results can be obtained by subtracting the other shape instead of the intersection:
```golang
fmt.Println(red.Difference(blue))

// Result
[[{260 200} {248.54101966249684 164.7328848624516} {218.54101966249684 142.93660902229078} {212.54744396386434 142.93660902229078} {200.90169943749473 178.77852522924732} {150.90169943749476 215.10565162951536} {144.90812373886223 215.10565162951536} {151.45898033750314 235.2671151375484} {181.45898033750316 257.0633909777092} {218.54101966249684 257.0633909777092} {248.54101966249684 235.2671151375484} {260 200}]]
```

In the erroneous case, polygon being constructed by the DIFFERENCE operation fails to be closed, as the segment `{150.90169943749476 215.10565162951536} {144.90812373886223 215.10565162951536}` does not satisfy the `e.other.inside` condition in [clipper.go](https://github.com/ctessum/polyclip-go/blob/master/clipper.go#L246):

```golang
case DIFFERENCE:
	if (e.polygonType == _SUBJECT && !e.other.inside) ||
		(e.polygonType == _CLIPPING && e.other.inside) {
		connector.add(e.segment())
	}
```

It tends to happen only at certain intersections (for instance, if the shapes are created with 18 sides instead of 10). Beyond that, I don't know enough about the algorithm to pinpoint the exact cause.

Thank you for your help!

**Comment by ctessum** [comment]
I guess this is probably caused by a floating point precision issue. Would you mind trying whether changing the tolerance [here](https://github.com/ctessum/polyclip-go/blob/master/clipper.go#L405) to a smaller or larger value fixes the problem?

**Comment by oceanful** [comment]
Thanks Chris.

I bumped it up to 3e-6 and that doesn't fix the issue; it's possible that it's an ordering issue with intersections that divide segments. Here's an expanded view (the issue is reproducible with other sizes of the polygons):

![intersection](https://user-images.githubusercontent.com/35951082/57051187-24eba400-6c35-11e9-9637-e3f3e5b0a096.png)

What always happens is that segment **A** (from the intersection) divides segment **B** (from the red shape) into **B'** and **B''**.  

Segment **B'** is (correctly) dropped by virtue of being `type=_SUBJECT,inside=true`.
Segment **B''** is (correctly) added by virtue of being `type=_SUBJECT,inside=false`.

However Segment **A** is then dropped by virtue of being `type=_CLIPPING,inside=false`.

In fact, in the above picture, the difference operation fails for both shapes:

```golang
blue := geom.Point{X: 120.0, Y: 120.0}.Buffer(200.0, sides)
red := geom.Point{X: 250.0, Y: 280.0}.Buffer(140.0, sides)
intersection := blue.Intersection(red)

fmt.Println(red.Difference(intersection))
fmt.Println(blue.Difference(intersection))

// Result
[]
[]
```

**Comment by oceanful** [comment]
This may be interesting ... I found a case that sometimes works and sometimes doesn't:

```golang
red := geom.Point{X: 120.0, Y: 120.0}.Buffer(200.0, sides)
blue := geom.Point{X: 220.0, Y: 280.0}.Buffer(140.0, sides)
intersection := red.Intersection(blue)

fmt.Println(red.Difference(intersection))

// Result is sometimes:
[[{360 280} {333.26237921249265 197.71006467905374} {263.2623792124926 146.8520877186785} {302.10558968045666 175.0733320479174} {281.80339887498945 237.55705045849464} {181.80339887498948 310.21130325903073} {89.81624747772447 310.21130325903073} {80 280} {106.73762078750735 362.28993532094626} {176.73762078750738 413.1479122813215} {263.26237921249265 413.1479122813215} {333.26237921249265 362.28993532094626} {360 280}]]

// And sometimes:
[]
```

The difference appears to be the order in which the segments are processed; it looks like `endpointLess()` does not define a strict ordering.

With the following ordering, the resulting polygon is successfully closed/computed:

```
Computed inside/inOut of {{80 280} left polygonType:1 other(inside:false):{106.73762078750735 197.71006467905377} inout:false inside:false edgeType:0}
Computed inside/inOut of {{80 280} left polygonType:0 other(inside:false):{106.73762078750735 197.71006467905377} inout:false inside:true edgeType:0}
Computed inside/inOut of {{80 280} left polygonType:1 other(inside:false):{89.81624747772447 310.21130325903073} inout:true inside:true edgeType:0}
Computed inside/inOut of {{80 280} left polygonType:0 other(inside:false):{106.73762078750735 362.28993532094626} inout:true inside:false edgeType:0}
+ Adding: {{89.81624747772447 310.21130325903073} right polygonType:1 other(inside:true):{80 280} inout:false inside:false edgeType:0}
Computed inside/inOut of {{89.81624747772447 310.21130325903073} left polygonType:1 other(inside:false):{181.80339887498948 310.21130325903073} inout:true inside:true edgeType:0}
Computed inside/inOut of {{106.73762078750735 197.71006467905377} left polygonType:1 other(inside:false):{176.73762078750735 146.85208771867852} inout:false inside:false edgeType:0}
Computed inside/inOut of {{106.73762078750735 197.71006467905377} left polygonType:0 other(inside:false):{176.73762078750735 146.85208771867852} inout:false inside:true edgeType:0}
+ Adding: {{106.73762078750735 362.28993532094626} right polygonType:0 other(inside:false):{80 280} inout:false inside:false edgeType:0}

...

Success: [[{360 280} {333.26237921249265 197.71006467905374} {263.2623792124926 146.8520877186785} {302.10558968045666 175.0733320479174} {281.80339887498945 237.55705045849464} {181.80339887498948 310.21130325903073} {89.81624747772447 310.21130325903073} {80 280} {106.73762078750735 362.28993532094626} {176.73762078750738 413.1479122813215} {263.26237921249265 413.1479122813215} {333.26237921249265 362.28993532094626} {360 280}]]
```

With a different ordering, the same segments are instead dropped and the polygon doesn't get closed:

```
Computed inside/inOut of {{80 280} left polygonType:0 other(inside:false):{106.73762078750735 197.71006467905377} inout:false inside:false edgeType:0}
Computed inside/inOut of {{80 280} left polygonType:1 other(inside:false):{106.73762078750735 197.71006467905377} inout:false inside:true edgeType:0}
Computed inside/inOut of {{80 280} left polygonType:0 other(inside:false):{106.73762078750735 362.28993532094626} inout:true inside:true edgeType:0}
Computed inside/inOut of {{80 280} left polygonType:1 other(inside:false):{89.81624747772447 310.21130325903073} inout:true inside:false edgeType:0}
- Dropping: {{89.81624747772447 310.21130325903073} right polygonType:1 other(inside:false):{80 280} inout:false inside:false edgeType:0}
Computed inside/inOut of {{89.81624747772447 310.21130325903073} left polygonType:1 other(inside:false):{181.80339887498948 310.21130325903073} inout:true inside:true edgeType:0}
Computed inside/inOut of {{106.73762078750735 197.71006467905377} left polygonType:1 other(inside:false):{176.73762078750735 146.85208771867852} inout:false inside:false edgeType:0}
Computed inside/inOut of {{106.73762078750735 197.71006467905377} left polygonType:0 other(inside:false):{176.73762078750735 146.85208771867852} inout:false inside:true edgeType:0}
- Dropping: {{106.73762078750735 362.28993532094626} right polygonType:0 other(inside:true):{80 280} inout:false inside:false edgeType:0}

...

Open chain: {false [{89.81624747772447 310.21130325903073} {181.80339887498948 310.21130325903073} {281.80339887498945 237.55705045849464} {302.10558968045666 175.0733320479174} {263.2623792124926 146.8520877186785} {333.26237921249265 197.71006467905374} {360 280} {333.26237921249265 362.28993532094626} {263.26237921249265 413.1479122813215} {176.73762078750738 413.1479122813215} {106.73762078750735 362.28993532094626}]}
```

The (currently non-deterministic) ordering determines whether the `_CLIPPING` segment is considered `inside` or not.

Is this a useful clue?

**Comment by oceanful** [comment]
The non-determinism scenario may be a separate issue. I was able to workaround it by breaking ties in `endpointLess()` by replacing the final `return e1.above(e2.other.p)` statement with a tie-breaker when `signedArea == 0` that will `return e1.polygonType == _SUBJECT` . (And I have no idea as to the general correctness of that solution).

Regardless, the workaround only addresses the non-determinism for the cases like `blue.X = 220.0`. The `blue.X = 250.0` case still reliably fails; so I think they are separate issues.

**Comment by oceanful** [comment]
The `red.X = 250.0` is due to floating point imprecision when segments are divided. When the endpoints of the divided segments don't exactly match existing endpoints, the connector fails to close the polygon. I have a [pull request](https://github.com/ctessum/polyclip-go/pull/1) for fixing that.

The remaining issues appears to be a flaw in the way `endpoint.inside` is calculated, particularly when the subject and clipping have colinear or intersecting segments. One clear manifestation of this is when two colinear segments share a left endpoint; the `endpointLess()` algorithm evaluates them as equal, so sometimes the subject's segment will be processed first, and sometimes the clipping's segment will be processed first; the two cases result in different outcomes.

I'm still looking into how to address the latter problem.

**Comment by oceanful** [comment]
One issue is caused by `findIntersection()` not correctly detecting overlapping segments. It seems to be caused by [this commit](https://github.com/ctessum/polyclip-go/commit/74289fd08b1534d9e06fe112dc2fd1250bd02e61#diff-3e34e6f7db69fccb577aa6db5c4643efR310) which changed the `sqrEpsilon` tolerance for detecting parallel lines from 1e-7 to 0. Bumping it up to something like 1e-15 fixes the particular problem.

Was setting the value to 0 crucial to infinite loop bug that the change was addressing? Or can it be a small value similar to those used for floating point tolerances?

**Comment by oceanful** [comment]
Setting the `sqrEpsilon` to a non-zero value does tickle the infinite loop case tested [here]( https://github.com/ctessum/polyclip-go/commit/ff18ec0ceeae35e804562066d6972af8ebed55db#diff-ec76632216527125009e98fef075db9eR157). What I don't understand is that this test existed before the commit that sets the sqrEpsilon to zero. So I wonder if there's a different way to address the problem of the second commit that doesn't impair the ability to detect parallel lines.

**Comment by oceanful** [comment]
It indeed looks like most of these issues arise from the changes to the intersection logic made to address infinite loops. The issues do not appear when running these operations with the akavel/polyclip-go library. It's probably worth re-examining those changes as they appear to result in correctness issues.

**Comment by ctessum** [comment]
Yeah, I think you're probably right about this. I don't really have a background in computational geometry; I've just been trying to keep this running well enough for my purposes. This library hasn't really been designed to be robust to floating point precision issues, but as you can see my attempts so far to fix that have ended up causing as many problems as they've fixed. The infinite loop issue is really not acceptable for my use case, though, so I can't just revert everything.

**Comment by oceanful** [comment]
No worries. I've made some progress with a different approach to addressing infinite loops. I'll keep you posted!

**Comment by ctessum** [comment]
Great, thanks!

**Comment by oceanful** [comment]
Fixed after rebasing geom on top of changes referenced in https://github.com/oceanful/polyclip-go/pull/1#issuecomment-491567847.
