### ISSUE TITLE
Certain scenarios with overlapping segments cause polygons to be dropped.

### ISSUE THREAD

**Issue by oceanful** [ctessum/geom#9]
Just a heads up; I fixed an edge case (pun intended ;) in the original polyclip-go library that wasn't properly handling overlapping edges in certain scenarios. We've successfully eliminated all of our dropped-polygon problems with this fix.

https://github.com/oceanful/polyclip-go/commit/7000f73ff15d5dede507dd4d5644a8f51b9e0823

Feel free to incorporate if you wish!

**Comment by kirillrdy** [comment]
@oceanful  Thank you very much for your fix. I owe you a beer or two :beers:

**Comment by oceanful** [comment]
@kirillrdy Happy to contribute. Cheers!  🍻

**Comment by ctessum** [comment]
Thanks! Fixed in v0.2.11.
